name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_KEY }}
  CLOUDFLARE_ACCOUNT_ID: ${{ vars.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./.github/actions/setup-pnpm

      - name: Run tests
        run: pnpm test

      - name: Build extension zip
        run: |
          pnpm --filter @majsoul-log-bot/extension zip
          cp extension/.output/*-chrome.zip public/majsoul-log-extension.zip

      - name: Run D1 Migrations
        run: pnpm exec wrangler d1 migrations apply majsoul-log --remote

      - name: Deploy
        run: pnpm exec wrangler deploy
